# Generated by Django 5.2.4 on 2025-07-23 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Préstamo"
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                (
                    "monto_original",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[("mensual", "Mensual"), ("semanal", "Semanal")],
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=datetime.date.today)),
                (
                    "tasa_interes_anual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("ultimo_pago", models.DateField(blank=True, null=True)),
                (
                    "plazo_periodos",
                    models.IntegerField(default=60, verbose_name="Plazo en Periodos"),
                ),
                (
                    "pago_fijo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Pago Fijo (para modo fixed_payment)",
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("fixed_term", "Fixed Term"),
                            ("fixed_payment", "Fixed Payment"),
                        ],
                        default="fixed_term",
                        max_length=20,
                        verbose_name="Modo de Cálculo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pago", "Pago"),
                            ("incremento_capital", "Incremento de Capital"),
                            ("interes_cargo", "Cargo de Interés"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="prestamos.prestamo",
                    ),
                ),
            ],
        ),
    ]
