# Generated by Django 5.2.4 on 2025-07-23 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prestamos.cliente"
            ),
        ),
    ]
