# Generated by Django 5.2.4 on 2025-07-26 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0002_alter_prestamo_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestamo",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="prestamo",
            name="pago_fijo",
        ),
        migrations.RemoveField(
            model_name="prestamo",
            name="plazo_periodos",
        ),
        migrations.AddField(
            model_name="prestamo",
            name="nombre_cliente",
            field=models.CharField(default="Cliente Anónimo", max_length=200),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="pago_mensual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="plazo_meses",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prestamos.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="modo",
            field=models.CharField(
                choices=[
                    ("fixed_term", "Fixed Term"),
                    ("fixed_payment", "Fixed Payment"),
                ],
                default="fixed_payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="tipo_pago",
            field=models.CharField(default="mensual", max_length=20),
        ),
    ]
