# Generated by Django 5.2.4 on 2026-07-03 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0004_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prestamo",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario propietario del préstamo. Aísla los datos entre cuentas.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prestamos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Pago",
        ),
    ]
