# Generated by Django 5.2.4 on 2026-07-03 18:29

from django.db import migrations


def assign_owner(apps, schema_editor):
    """Asigna los préstamos sin dueño al primer superusuario (o al primer
    usuario si no hay superusuario). Evita perder acceso a los datos
    existentes tras introducir el aislamiento por usuario."""
    Prestamo = apps.get_model("prestamos", "Prestamo")
    User = apps.get_model("auth", "User")

    huerfanos = Prestamo.objects.filter(owner__isnull=True)
    if not huerfanos.exists():
        return

    owner = User.objects.filter(is_superuser=True).order_by("id").first() \
        or User.objects.order_by("id").first()
    if owner is None:
        # No hay usuarios; se dejan sin dueño (no serán visibles hasta reasignarse).
        return
    huerfanos.update(owner=owner)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0005_add_owner_to_prestamo"),
    ]

    operations = [
        migrations.RunPython(assign_owner, noop),
    ]
