# Generated by Django 5.2.4 on 2026-07-03 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0006_assign_existing_prestamos_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario propietario. Aísla la PII del cliente entre cuentas.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_nombre", models.CharField(blank=True, max_length=150)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("editar", "Editar"),
                            ("borrar", "Borrar"),
                            ("pago", "Registrar pago"),
                            ("incremento", "Registrar incremento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("objeto_id", models.IntegerField(blank=True, null=True)),
                ("detalle", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
