# Generated by Django 5.2.4 on 2026-07-03 18:59

from django.db import migrations


def assign_owner(apps, schema_editor):
    """Asigna cada Cliente sin dueño al owner de alguno de sus préstamos; si no
    tiene préstamos, al primer superusuario (o primer usuario). Mantiene la PII
    accesible tras introducir el aislamiento por usuario."""
    Cliente = apps.get_model("prestamos", "Cliente")
    Prestamo = apps.get_model("prestamos", "Prestamo")
    User = apps.get_model("auth", "User")

    huerfanos = Cliente.objects.filter(owner__isnull=True)
    if not huerfanos.exists():
        return

    fallback = User.objects.filter(is_superuser=True).order_by("id").first() \
        or User.objects.order_by("id").first()

    for cliente in huerfanos:
        prestamo = Prestamo.objects.filter(cliente=cliente, owner__isnull=False).first()
        owner = prestamo.owner if prestamo else fallback
        if owner is not None:
            cliente.owner = owner
            cliente.save(update_fields=["owner"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0007_add_owner_cliente_and_auditoria"),
    ]

    operations = [
        migrations.RunPython(assign_owner, noop),
    ]
