# Generated by Django 5.2.4 on 2026-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_assign_existing_clientes_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='concepto',
            field=models.CharField(blank=True, help_text='Qué se compró o para qué fue el dinero. Ej: "Terreno en Misiones".', max_length=200),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='rol',
            field=models.CharField(choices=[('prestamo', 'Préstamo otorgado (me deben)'), ('deuda', 'Deuda propia (yo debo)')], default='prestamo', max_length=10),
        ),
    ]
