# Generated by Django 5.2.4 on 2026-08-09 16:46

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_prestamo_concepto_prestamo_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('cetesdirecto', 'CetesDirecto'), ('briq', 'Briq.mx'), ('otra', 'Otra')], default='cetesdirecto', max_length=20)),
                ('nombre', models.CharField(help_text='Ej: "CETES 28 días" o "Torre Guadalajara".', max_length=200)),
                ('tipo', models.CharField(choices=[('descuento', 'A descuento (CETES, Bondes)'), ('tasa_fija', 'Tasa fija a plazo (Briq, pagarés)'), ('fondo', 'Fondo de inversión (BONDDIA, ENERFIN)')], default='descuento', max_length=20)),
                ('monto_invertido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
                ('tasa_anual', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Tasa nominal anual en %. No aplica a fondos.', max_digits=6)),
                ('plazo_dias', models.IntegerField(default=0, help_text='Días al vencimiento. 0 en fondos (liquidez abierta).')),
                ('base_dias', models.IntegerField(default=360, help_text='360 para CETES (convención Banxico); 365 para el resto.')),
                ('valor_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor capturado. Obligatorio en fondos, que no se proyectan.', max_digits=15, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Usuario propietario. Aísla el portafolio entre cuentas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('aportacion', 'Aportación'), ('retiro', 'Retiro'), ('rendimiento', 'Rendimiento cobrado')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='prestamos.inversion')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
