# Generated by Django 5.2.4 on 2026-08-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_inversion_movimientoinversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='fecha_valor',
            field=models.DateField(blank=True, help_text='Fecha a la que corresponde el valor capturado. Las aportaciones y retiros posteriores se suman o restan sobre él. Por defecto, la de compra.', null=True),
        ),
    ]
