# Generated by Django 5.2.4 on 2026-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_inversion_fecha_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='capitalizar_intereses',
            field=models.BooleanField(default=False, help_text='Si está activo, el interés que no se paga se acumula a la base del período siguiente (interés compuesto) y los pagos liquidan primero los intereses devengados y después la cuota. Apagado, cada período devenga sólo sobre la cuota no cubierta.', verbose_name='Capitalizar intereses no pagados'),
        ),
    ]
