# Generated by Django 5.2.4 on 2026-10-10 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_prestamo_capitalizar_intereses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='movimientoinversion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
